package com.ingescape;

public enum WebSocketEvent {
	IGS_WEB_SOCKET_TRY_CONNECT,
	//IGS_WEB_SOCKET_FAIL_CONNECT,
	IGS_WEB_SOCKET_FAILED,
	IGS_WEB_SOCKET_OPENED,
	IGS_WEB_SOCKET_CLOSING,
	IGS_WEB_SOCKET_CLOSED;
}
